version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgresql_local_testing'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      #- ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql    
    environment:
      - POSTGRES_USER=sysdba
      - POSTGRES_PASSWORD=MasterCloud
      - POSTGRES_DB=local_test
    ports:
      - '5432:5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"      
  #volumes: 
    #postgres_data:
      #external: true